import Head from 'next/head'
import Image from 'next/image'
import { Inter } from '@next/font/google'
import styles from '../styles/Home.module.css'



const inter = Inter({ subsets: ['latin'] })


export default function Home() {
  return (
    <>
      <Head>
        <title>Arjun Aditya</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="favicon.ico" />
      </Head>
      <main className={styles.main}>
        <div className={styles.header}>
          <h1 className={styles.arjun}>Arjun Aditya </h1>
          </div>
        <hr className={styles.hr}></hr>
        <div className={styles.window}>
          <div className={styles.windowToolbar}>
            <div className={styles.aaa}>
                <i className={styles.icon1}></i>
                <i className={styles.icon2}></i>
                <i className={styles.icon3}></i>
                <h3 className={styles.toolbarTitle}>INTERESTING STUFF 😃👍</h3>
            </div>
          </div>
          <ul className={styles.content1}>
            <div className={styles.bullet}>
              <p className={styles.emoji}>💡</p>
              <div>
                <p className={styles.stuff}>Permit me to introduce myself, I am an ambitious and accomplished individual with a passion for technology and finance. I have several years of experience in the field of programming, particularly in the realm of full stack development. My journey into the world of coding began at a young age.</p>
              </div>
            </div>
            <div className={styles.bullet}>
              <p className={styles.emoji}>💡</p>
              <div>
                <p className={styles.stuff}>I've always been able to tackle new challenges with my workaholic nature.</p>
              </div>
            </div>
              <div className={styles.bullet}>
              <p className={styles.emoji}>💡</p>
              <div>
                <p className={styles.stuff}>I also have an ability to turn websites into successful ventures, having built and grown several websites to thousands of monthly viewers and successfully sold them on Flippa. To be specific, I can fit in any industry on the IT.</p>
              </div>
            </div>
            <div className={styles.bullet}>
              <p className={styles.emoji}>💡</p>
              <div>
                <p className={styles.stuff}>Furthermore, I have also gained a wealth of knowledge in different sectors (particularly technology, business world and in the realm of trading stocks and commodities) This has provided me with a nuanced perspective on the financial markets and has enabled me to acquire a profound understanding of the tech startup industry.</p>
              </div>
            </div>
            <div className={styles.bullet}>
              <p className={styles.emoji}>💡</p>
              <div>
                <p className={styles.stuff}>I am renowned for my capacity to handle stress and my fortitude in the face of adversity, which, coupled with my workaholic nature, makes me a valuable asset to any organization. My penchant for finance and startup podcasts keeps me abreast of the latest trends and advancements, thereby providing me with a competitive edge.</p>
              </div>
            </div>
          </ul>
        </div>
        <hr className={styles.hr}></hr>

        <marquee className={styles.rickcontainer} direction="right" scrollamount="7"><img className={styles.rickyy} src="rickyy.gif" width="100" /></marquee>


        <div className={styles.myskills}>
          <div className={styles.skills}>
            <div className={styles.skills1}>
              <h1 className={styles.here}><img className={styles.here1} src="cat.gif" height="60" />HERE ARE MY SKILLS</h1>
        
        <div className={styles.skillcontainer}>
          <div className={styles.skillcontainer1}>
                  <h2>Hard Skills</h2>
                  <ul>
                    <li>Proficiency in HTML, Handlebars, Sass, MDX, JavaScript, Reactjs, Nextjs and SQL </li>
                    <li>Experience with front-end build tools like Webpack, Esbuild, and Gulp</li>
                    <li>Understanding of SEO Practices </li>
                    <li>UI/UX Designing ( Figma & Penpot )</li>
                    <li>Video Editing ( Final Cut Pro )</li>
                    <li>Graphic Designing ( <a href=''>Examples</a> )</li>
                    <li>Sales and marketing ( Selling services through my <a href=''>web agency</a> )</li>
                  </ul>      
          </div>
          <div className={styles.skillcontainer1}>
                  <h2>Soft Skills</h2>
                  <ul>
                    <li>Knowledge of Chrome Developer Tools.</li>
                    <li>Knowledge of building Themes for <a href='https://Ghost.org'>Ghost.org</a>.</li>
                    <li>Technical Anaylisis of Candlesticks chart.</li>
                    <li>Workaholic Nature with Problem solving skills.</li>
                    <li>Twitter SEO.</li>
                    <li>Ability to handle stress and pressure.</li>
                    <li>Ability to work well within a team( Spent time working with programmers on discord ).</li>
                    <li>Copywriting. </li>

                  </ul>   
          </div>
          <div className={styles.skillcontainer1}>
                  <h2>My Exposure</h2>
                  <ul>
                    <li>Investing in Web3 Industry From 2020 - Present</li>
                    <li>Started a <a href='https://www.youtube.com/channel/UCj4-RjkD3nD_PVOl4EdmQxQ'>Youtube Channel</a> (Experience in Youtube SEO & Video Editing)</li>
                    <li>Started <a href='https://web.archive.org/web/20220124055848/https://www.nerdclump.com/'>Nerd Clump</a> in 2021 sold it on Flippa</li>
                    <li>Trading in F&O from 2022 - Present</li>
                    <li>Learning about Macroeconomics from 2022 - Present</li>
                    <li>Startup podcasts are my favorite</li>
                    <li>Lost about $3.6k in futures at the age of 14</li>
                  </ul>       
                </div>
                          <div className={styles.skillcontainer1}>
                  <h2>Still Learning</h2>
                  <ul>
                  <li>Jamstack</li>
                  <li>Three.js</li>
                  <li>Typescript</li>
                  <li>Rust for Solana Ecosystem</li>
                  <li>Mongodb</li>
                  <li>Express.js</li>
                  <li>Nodejs</li>
                  <p> Will take about 10-12 months to become good at them</p>
                  </ul>       
                </div>
              </div>
              </div>
              </div>

        </div>
        <div className={styles.dark}>
          <div className={styles.hirewindow}>
          <h1 className={styles.here}><img className={styles.here1} src="hire.gif" height="80" />Why Should You Hire Me ?</h1>
            <p className={styles.hireme}>You should hire me because I have a proven track record of being able to handle stress and adversity. My workaholic nature and problem-solving skills make me a valuable asset to any organization. My background in finance and startups, as well as my listening to related podcasts, keeps me informed of the latest trends and developments, which gives me a competitive edge. My experience in web development and design, front-end build tools, SEO practices, UI/UX design, video editing, graphic design and sales and marketing will also be a great asset to your company. I have a team-oriented attitude, as I have experience working with programmers on discord, which will make me a great addition to your team.</p>
            </div>
        </div>
        <marquee className={styles.guitarcontainer} direction="left" scrollamount="4"><img className={styles.guitar} src="guitar.gif" width="70" /></marquee>
        <img className={styles.arjunimg} src="Homer-Animated.gif" width="90" /> 

      </main>
    </>
  )
}
